language : python
python:
- 3.6

install :
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - pip install mock
  - pip install coveralls
  - pip install responses
  
script : 
 - coverage run --source=mypkg --with-coverage main/test.py test

after_success:
 - coveralls

# safelist
branches:
  only:
  - master
  
notifications:
  email:
    recipients:
      - beta1360@naver.com
