language : python
python:
- 3.6

install :
  - pip install -r requirements.txt
  - pip install coveralls
  
script : 
 - coverage run --source=mypkg main/test.py test

after_success:
  coveralls

# safelist
branches:
  only:
  - master
  
notifications:
  email:
    recipients:
      - beta1360@naver.com
