language : python
python:
- 3.3
- 3.4
- 3.5
- 3.6
- 3.6.3

install :
  - pip install -r requirements.txt
  - pip install coveralls
  
script : 
 - cd main && python3 test.py

after_success:
  coveralls

# safelist
branches:
  only:
  - master
