language : python
python:
- 3.6

install :
  - pip install -r requirements.txt
  
script : 
 - cd main && python3 test.py

after_success:
 - coveralls

# safelist
branches:
  only:
  - master
  
notifications:
  email:
    recipients:
      - beta1360@naver.com
